blank_issues_enabled: true
contact_links:
  - name: 💬 Ask question
    url: https://github.com/AvaloniaCommunity/Material.Avalonia/discussions
    about: Get in touch with the whole community. Ask a question about using something
