<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="MaterialThemeIncludeTreeDataGrid" Value="true" />
    <TrimmerRootAssembly Include="Material.Avalonia.TreeDataGrid" RootMode="library" />
  </ItemGroup>
</Project>
