name: Build and publish

on:
    push:
        branches:
            - '!master'
            - '!main'
            - '!release/**'

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 10
            - name: Build and Publish
              uses: SKProCH/CommonWorkflows/actions/build-publish@main
              with:
                  only-build: true
                  nuget-user: ${{ secrets.NUGET_USER }}